package com.imperative;

enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE,
    RIGHT_BRACE, COMMA, DOT, MINUS, PLUS,
    SLASH, STAR, PERCENT,

    EQUAL, EQUAL_EQUAL, SLASH_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL, DOT_DOT,

    IDENTIFIER, SEMICOLON, COLON, WALRUS,
    TYPE_BOOLEAN, TYPE_INTEGER, TYPE_REAL,
    TYPE_RECORD, TYPE_ARRAY,

    AND, ARRAY, BOOLEAN, ELSE, END, FALSE, FOR,
    IF, IN, INTEGER, IS, LOOP, NOT, OR, PRINT,
    REAL, RECORD, RETURN, REVERSE, ROUTINE, THEN, TRUE,
    TYPE, VAR, WHILE, XOR,

    EOF
}
